apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: homeassistant
  hostPath:
    path: /mnt/nvme/homeassistant-config