apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: homeassistant