apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr
  namespace: media
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sonarr
  hostPath:
    path: /mnt/nvme/sonarr-config