apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr
  namespace: media
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: radarr
  hostPath:
    path: /mnt/nvme/radarr-config