apiVersion: v1
kind: PersistentVolume
metadata:
  name: uptime-kuma
  namespace: observability
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: uptime-kuma
  hostPath:
    path: /mnt/data/uptime-kuma-config