# Persistent Volume for Plex Configuration
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex
  namespace: media
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: plex
  hostPath:
    path: /mnt/nvme/plex-config
---
# Persistent Volume for Movies
apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies
  namespace: media
spec:
  capacity:
    storage: 100Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: movies
  hostPath:
    path: /mnt/raid/movies
---
# Persistent Volume for Series
apiVersion: v1
kind: PersistentVolume
metadata:
  name: series
  namespace: media
spec:
  capacity:
    storage: 100Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: series
  hostPath:
    path: /mnt/raid/series
---
# Persistent Volume for Downloads
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads
  namespace: media
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: downloads
  hostPath:
    path: /mnt/nvme/downloads